In [332]:
%run carbon_tracker.py

In [333]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Data

In [334]:
update_project_name("Pre-processing")

[codecarbon ERROR @ 10:33:10] You first need to start the tracker.


In [335]:
df = pd.read_csv("final_depression_dataset_1.csv")

In [336]:
df.head()

Name  Gender  Age       City Working Professional or Student  \
0    Pooja  Female   37  Ghaziabad            Working Professional   
1  Reyansh    Male   60     Kalyan            Working Professional   
2    Manvi  Female   42     Bhopal            Working Professional   
3     Isha  Female   44      Thane            Working Professional   
4    Aarav    Male   48     Indore            Working Professional   

          Profession  Academic Pressure  Work Pressure  CGPA  \
0            Teacher                NaN            2.0   NaN   
1  Financial Analyst                NaN            4.0   NaN   
2            Teacher                NaN            2.0   NaN   
3            Teacher                NaN            3.0   NaN   
4     UX/UI Designer                NaN            4.0   NaN   

   Study Satisfaction  Job Satisfaction Sleep Duration Dietary Habits Degree  \
0                 NaN               4.0      7-8 hours       Moderate     MA   
1                 NaN               3.0      5-6 hours      Unhealthy  B.Com   
2                 NaN               3.0      5-6 hours       Moderate  M.Com   
3                 NaN               5.0      7-8 hours        Healthy     MD   
4                 NaN               3.0      7-8 hours       Moderate     BE   

  Have you ever had suicidal thoughts ?  Work/Study Hours  Financial Stress  \
0                                    No                 6                 2   
1                                   Yes                 0                 4   
2                                    No                 0                 2   
3                                   Yes                 1                 2   
4                                   Yes                 6                 5   

  Family History of Mental Illness Depression  
0                               No         No  
1                              Yes         No  
2                               No         No  
3                              Yes         No  
4                              Yes         No

In [337]:
print(len(df))

2556


In [338]:
empty_rows = df.isnull().all(axis=1).sum()
print (empty_rows)

0


In [339]:
numeric_columns = ['Age', 'Academic Pressure', 'Work Pressure', 'CGPA', 
                   'Job Satisfaction', 'Work/Study Hours', 'Financial Stress']

# Vérifier les valeurs négatives uniquement dans les colonnes numériques
negative_rows = (df[numeric_columns] < 0).any(axis=1).sum()

print(negative_rows)


0


In [340]:
print(df.dtypes)

Name                                      object
Gender                                    object
Age                                        int64
City                                      object
Working Professional or Student           object
Profession                                object
Academic Pressure                        float64
Work Pressure                            float64
CGPA                                     float64
Study Satisfaction                       float64
Job Satisfaction                         float64
Sleep Duration                            object
Dietary Habits                            object
Degree                                    object
Have you ever had suicidal thoughts ?     object
Work/Study Hours                           int64
Financial Stress                           int64
Family History of Mental Illness          object
Depression                                object
dtype: object


In [341]:
print(df.isna().sum())


Name                                        0
Gender                                      0
Age                                         0
City                                        0
Working Professional or Student             0
Profession                                673
Academic Pressure                        2054
Work Pressure                             502
CGPA                                     2054
Study Satisfaction                       2054
Job Satisfaction                          502
Sleep Duration                              0
Dietary Habits                              0
Degree                                      0
Have you ever had suicidal thoughts ?       0
Work/Study Hours                            0
Financial Stress                            0
Family History of Mental Illness            0
Depression                                  0
dtype: int64


In [342]:
print(df['Gender'].unique())


['Female' 'Male']


In [343]:
print(df['Age'].unique())


[37 60 42 44 48 30 56 35 21 57 54 51 18 31 28 58 47 50 46 38 25 45 23 53
 19 34 49 20 43 22 33 36 24 41 29 27 52 26 59 55 40 32 39]


In [344]:
print(df['Financial Stress'].unique())


[2 4 5 3 1]


In [345]:
print(df['Work/Study Hours'].unique())


[ 6  0  1 12  3 11 10  8  7  9  5  2  4]


In [346]:
print(df['Degree'].unique())


['MA' 'B.Com' 'M.Com' 'MD' 'BE' 'MCA' 'BA' 'LLM' 'BCA' 'Class 12' 'B.Ed'
 'M.Tech' 'LLB' 'B.Arch' 'ME' 'MBA' 'M.Pharm' 'MBBS' 'PhD' 'BSc' 'MSc'
 'MHM' 'BBA' 'BHM' 'B.Tech' 'M.Ed' 'B.Pharm']


In [347]:
print(df['Dietary Habits'].unique())


['Moderate' 'Unhealthy' 'Healthy']


In [348]:
print(df['Depression'].unique())


['No' 'Yes']


In [349]:
print(df['Family History of Mental Illness'].unique())

['No' 'Yes']


In [350]:
print(df['Sleep Duration'].unique())

['7-8 hours' '5-6 hours' 'More than 8 hours' 'Less than 5 hours']


In [351]:
print(df['Working Professional or Student'].unique())	

['Working Professional' 'Student']


In [352]:
#Cumulative Grade Point Average(CGPA)
print(df['CGPA'].min())	
print(df['CGPA'].max())	

# Compter les valeurs de CGPA < 5
count_less_than_5 = (df['CGPA'] < 5).sum()
print(f"Nombre de CGPA < 5 : {count_less_than_5}")

# Compter les valeurs de CGPA > 5
count_greater_than_5 = (df['CGPA'] > 5).sum()
print(f"Nombre de CGPA > 5 : {count_greater_than_5}")

5.03
10.0
Nombre de CGPA < 5 : 0
Nombre de CGPA > 5 : 502


In [353]:
df['CGPA'].fillna(df['CGPA'].median(), inplace=True)

In [354]:
# Dictionnaire de conversion des valeurs textuelles en nombres
sleep_mapping = {
    'More than 8 hours': 9,  
    '5-6 hours': 5.5,        
    'Less than 5 hours': 4, 
    '7-8 hours': 7.5,        
    '6-7 hours': 6.5         
}

# Remplacement des valeurs dans la colonne Sleep Duration
df['Sleep Duration'] = df['Sleep Duration'].map(sleep_mapping)

# Vérification des valeurs uniques après conversion
print(df['Sleep Duration'].unique())


[7.5 5.5 9.  4. ]


In [355]:
df['Profession'].fillna('None', inplace=True)

In [364]:
print(df['Academic Pressure'].unique())	

[3. 2. 4. 1. 5.]


In [ ]:
print(df['Work Pressure'].unique())	

In [356]:
df['Academic Pressure'].fillna(df['Academic Pressure'].median(), inplace=True)

In [357]:
df['Work Pressure'].fillna(df['Work Pressure'].median(), inplace=True)

In [358]:
print(df['Study Satisfaction'].unique())	

[nan  4.  5.  3.  2.  1.]


In [360]:
print(df['Job Satisfaction'].unique())	

[ 4.  3.  5.  2.  1. nan]


In [ ]:
# Séparer les données en deux groupes : "Yes" et "No" dans la colonne 'Depression'
depression_yes = df[df['Depression'] == 'Yes']
depression_no = df[df['Depression'] == 'No']

# Calculer la médiane pour chaque groupe pour les colonnes concernées
medians_yes = depression_yes[['Job Satisfaction', 'Study Satisfaction', 'Work Pressure', 'Academic Pressure']].median()
medians_no = depression_no[['Job Satisfaction', 'Study Satisfaction', 'Work Pressure', 'Academic Pressure']].median()

# Imputer les valeurs manquantes dans le DataFrame original
for col in ['Job Satisfaction', 'Study Satisfaction', 'Work Pressure', 'Academic Pressure']:
    # Imputer pour le groupe "Yes"
    df.loc[(df['Depression'] == 'Yes') & (df[col].isnull()), col] = medians_yes[col]
    
    # Imputer pour le groupe "No"
    df.loc[(df['Depression'] == 'No') & (df[col].isnull()), col] = medians_no[col]


In [362]:
print(df.isna().sum())

Name                                     0
Gender                                   0
Age                                      0
City                                     0
Working Professional or Student          0
Profession                               0
Academic Pressure                        0
Work Pressure                            0
CGPA                                     0
Study Satisfaction                       0
Job Satisfaction                         0
Sleep Duration                           0
Dietary Habits                           0
Degree                                   0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         0
Family History of Mental Illness         0
Depression                               0
dtype: int64


### Visualisation

In [363]:
stop_tracker()